### ISSUE TITLE
识别二维码时出错

### ISSUE THREAD

**Issue by qutz** [hetian9288/flutter_qr_reader#1]
![image](https://user-images.githubusercontent.com/23071957/59589404-71733c00-911c-11e9-8e77-ef000dbd0f8f.png)

**Comment by hetian9288** [comment]
看这里 [zxing/zxing#1170](https://github.com/zxing/zxing/issues/1170)

**Comment by qutz** [comment]
那应该修改一下example

**Comment by hetian9288** [comment]
直接并到主分支了 试试吧
