### ISSUE TITLE
Can I use it on android.x now?

### ISSUE THREAD

**Issue by oversuperman** [hetian9288/flutter_qr_reader#13]
error message:
Error on line 2, column 91: Mapping values are not allowed here. Did you miss a colon earlier?

  ╷
2 │ description: QR code (scan QRCode and picture) recognition 锛圓ndroidView/UiKitView锛?version: 1.0.1
  │                                                                                           ^
  ╵
pub get failed (65)

dependencie is this repo with branch master:latest

**Comment by hetian9288** [comment]
I don't understand your question

You can try the flitter: dev fork
