### ISSUE TITLE
使用例子中的独立UI扫描之后，无法返回

### ISSUE THREAD

**Issue by chenjuyu** [hetian9288/flutter_qr_reader#28]
使用例子中的独立UI扫描之后，无法返回，点确定后，还是停留在扫描界面，ScanViewDemo，
把这个    print('上下文pContext8888:${context}');
    _key.currentState.startScan();
    Navigator.pop(context,data);
 把这两个放在showCupertinoDialog方法外，会出现黑屏的现像，这个插件作者维护吗？？
 await showCupertinoDialog();

**Comment by hetian9288** [comment]
目前使用中每发现这个问题 
你可以把你的环境 代码发一下

**Comment by chenjuyu** [comment]
代码就是你demo里面例子，可能 是android 低版本的不兼容，环境如下

`[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.17763.864], locale zh-CN)
• Flutter version 1.9.1+hotfix.6 at D:\flutter
• Framework revision&nbsp;68587a0&nbsp;(9 weeks ago), 2019-09-13 19:46:58 -0700
• Engine revision b863200c37
• Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
• Android SDK at D:\AndroidSDK
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-29, build-tools 29.0.2
• ANDROID_HOME = D:\AndroidSDK
• Java binary at: D:\Android Studio\jre\bin\java
• Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
• All Android licenses accepted.

[√] Android Studio (version 3.5)
• Android Studio at D:\Android Studio
• Flutter plugin version 41.0.2
• Dart plugin version 191.8593
• Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
• MOGOLIA • F2C7N15429014716 • android-arm • Android 6.0 (API 23)



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月20日(星期三) 下午2:45
收件人:&nbsp;"hetian9288/flutter_qr_reader"<flutter_qr_reader@noreply.github.com&gt;;
抄送:&nbsp;"CHEN"<2498525982@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [hetian9288/flutter_qr_reader] 使用例子中的独立UI扫描之后，无法返回 (#28)




目前使用中每发现这个问题
 你可以把你的环境 代码发一下

**Comment by hetian9288** [comment]
例子中 扫码后 点确定是继续扫码 ；黑屏应该是重复pop导致；你可以使用 flutter_qr_reader.dart 提供的接口使用或者参考qrcode_reader_view.dart 修改

**Comment by chenjuyu** [comment]
哦，好的，我晚上回去再看看吧，只是学习，pop 重置不应该啊，我已经屏蔽了，弹框返回的确定那段代码 ，scanViewDemo 这个dart文件中，只有一个pop ，我看了下

输出，其实是已经返回上一个界面（widget）中了因为我打印了输出文字，但还弄不明白，为什么会黑屏





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月20日(星期三) 下午4:06
收件人:&nbsp;"hetian9288/flutter_qr_reader"<flutter_qr_reader@noreply.github.com&gt;;
抄送:&nbsp;"CHEN"<2498525982@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [hetian9288/flutter_qr_reader] 使用例子中的独立UI扫描之后，无法返回 (#28)




例子中 扫码后 点确定是继续扫码 ；黑屏应该是重复pop导致；你可以使用 flutter_qr_reader.dart 提供的接口使用或者参考qrcode_reader_view.dart 修改

**Comment by geekz-reno** [comment]
Hi, thank for this, but i can't make it to close if just using pop, i must use call popUntil to make it work. But the problem are i can't return data when using popUntil. 

any suggestion? 

thank
