### ISSUE TITLE
startScan isn't continued after scanned. 首次扫描有结果后无法继续扫描

### ISSUE THREAD

**Issue by AlexV525** [hetian9288/flutter_qr_reader#5]
When camera is running, log will print like this:
`E/Camera-JNI(10103): copyAndPost: off=0, size=1382400 msg=10`
After done scan at `onScan` like demo and run `startScan`, camera seems paused and not scanning, with no log printed further.

当相机调用时，会输出如上log，但当识别完成后再次启动`startScan`，相机看起来未正常继续调用而被暂停，log也没有继续输出。

`flutter doctor`:
```
[√] Flutter (Channel unknown, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.18362.175], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
```

**Comment by AlexV525** [comment]
This only appears in debug mode, release has no related issue for now.

仅出现在debug情况下，release暂无此情况。

**Comment by hetian9288** [comment]
无法复现你的情况  你可以试试 使用flutter的dev分支
