### ISSUE TITLE
IOS 没有图像，但能扫描

### ISSUE THREAD

**Issue by okchenyi** [hetian9288/flutter_qr_reader#7]

**Comment by derekcoder** [comment]
+1

**Comment by ggchxx** [comment]
<key>io.flutter.embedded_views_preview</key>
<true/> 
info.plist增加这个就可以了

**Comment by Katekko** [comment]
where @ggchxx ?
I can't find the location in the file? Can u send me a print?

**Comment by Katekko** [comment]
@hetian9288  You can close this now :D
